export enum RewardXpLedgerType {
  CHECKIN_DAILY = 'CHECKIN_DAILY',
  CHECKIN_SATURDAY_BONUS = 'CHECKIN_SATURDAY_BONUS',
  CHECKIN_SUNDAY_BONUS = 'CHECKIN_SUNDAY_BONUS',
  CHECKIN_FULL_WEEK_BONUS = 'CHECKIN_FULL_WEEK_BONUS',
  STREAK_MILESTONE = 'STREAK_MILESTONE',
  FREEZE_CONSUMED = 'FREEZE_CONSUMED',
}
